[tool.poetry]
name = "remover_fundo"
version = "0.1.0"
description = "Projeto para remover fundo de imagens"
authors = ["Seu Nome <caiojmagni@hotmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
rembg = "^2.0.0"
requests = "^2.25.1"
pillow = "^8.2.0"
onnxruntime = "^1.9.0"
